name: WIN10_22H2amd64
'on': workflow_dispatch
permissions:
  contents: write
jobs:
  WIN10_22H2amd64:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Build ISO from UUP dump package
        working-directory: .\WIN10_22H2amd64
        shell: cmd
        run: |
          uup_download_windows.cmd
          
      - name: Split Archive
        working-directory: .
        shell: pwsh
        run: |
          $iso = Get-ChildItem -Path ".\WIN10_22H2amd64" -Filter "*.iso" -File | Select-Object -First 1
          $hash = (Get-FileHash -Path $iso.FullName -Algorithm SHA256).Hash.ToLower()
          $hash8 = $hash.Substring($hash.Length - 8)
          $newName = "$($iso.BaseName)_$hash8.iso"
          $newPath = Join-Path -Path $iso.DirectoryName -ChildPath $newName
          Rename-Item -Path $iso.FullName -NewName $newName -Force
          $revisionName = "WIN10_22H2amd64"
          $isoBaseName = $iso.BaseName
          $revision = $isoBaseName.Split('-')[0]
          
          echo "ISO_NAME=$newName" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "ISO_PATH=$newPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "ISO_REVISION=$revision" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "REVISION_NAME=$revisionName" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "SHA256=$hash" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

          Write-Host "文件名: $newName"
          Write-Host "文件路径: $newPath"
          Write-Host "版本: $revision"
          Write-Host "SHA256: $hash"
          
          $outputZipFileName = "${revisionName}-${revision}.7z"
          # -v1820M
          7z a -t7z -v1280M -mx=0 ".\$outputZipFileName" ".\WIN10_22H2amd64\*.iso"
          Write-Host "Generated archive: .\$outputZipFileName"
          Write-Host "Split Archive Done..."
          
      - name: Delete Old Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: gh release delete ${{env.REVISION_NAME}} --cleanup-tag -y || true
      - name: Build New Release
        uses: softprops/action-gh-release@v3
        with:
          fail_on_unmatched_files: true
          overwrite_files: true
          body: |
            ## WIN10_22H2_amd64_Feature_Update_${{ env.ISO_REVISION }}
            - **Product**: ${{ env.ISO_NAME }}
            - **Version**: ${{ env.ISO_REVISION }}
            - **SHA256**: ${{ env.SHA256 }}
            - **Language**: ZH_CN
            ---
            > ⚠️ **Note**: This is a multi-volume archive (.7z.001, .7z.002...). Please download all parts before extracting.
          tag_name: ${{env.REVISION_NAME}}
          name: ${{ env.REVISION_NAME }}-${{ env.ISO_REVISION }}
          files: |
            *.7z.*
