name: WIN10_22H2amd64
on: workflow_dispatch
permissions:
  contents: write
jobs:
  WIN10_22H2amd64_FeatureUpdate:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Build ISO from UUP dump package
        working-directory: ./WIN10_22H2amd64
        shell: cmd
        run: |
          uup_download_windows.cmd
      - name: Split Archive
        working-directory: .
        shell: pwsh
        run: |
          $file = Get-ChildItem -Path .\WIN10_22H2amd64 -Filter "*.iso" -File | Select-Object -First 1
          $fileNameOnly = $file.Name
          $fullPath = $file.FullName
          $version = $fileNameOnly.Split('-')[0]
          $revisionName = "WIN10_22H2amd64"
          Add-Content -Path $env:GITHUB_ENV -Value "OUT_NAME=$fileNameOnly"
          Add-Content -Path $env:GITHUB_ENV -Value "OUT_PATH=$fullPath"
          Add-Content -Path $env:GITHUB_ENV -Value "OUT_REVISION=$version"
          Add-Content -Path $env:GITHUB_ENV -Value "REVISION_NAME=$revisionName"
          Write-Host "完整文件名: $fileNameOnly"
          Write-Host "完整路径: $fullPath"
          Write-Host "OUT_REVISION: $version"
          Write-Host "REVISION_NAME: $revisionName"
          $outputZipFileName = "${revisionName}-${version}.7z"
          7z a -t7z -v1820M -mx=0 ".\$outputZipFileName" ".\WIN10_22H2amd64\*.iso"
          Write-Host "Generated archive: .\$outputZipFileName"
          Write-Host "Split Archive Done..."
      - name: Delete Old Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: gh release delete ${{env.REVISION_NAME}} --cleanup-tag -y || true
      - name: Build New Release
        uses: softprops/action-gh-release@v3
        with:
          fail_on_unmatched_files: true
          overwrite_files: true
          body: |
            ## 🚀 Automated Release
            - **Product**: ${{ env.OUT_NAME }}
            - **Version**: ${{ env.OUT_REVISION }}
            - **Language**: ZH_CN
            ---
            > ⚠️ **Note**: This is a multi-volume archive (.7z.001, .7z.002...). Please download all parts before extracting.
          tag_name: ${{env.REVISION_NAME}}
          name: ${{ env.REVISION_NAME }}-${{ env.OUT_REVISION }}
          files: |
            *.7z.*
