name: Windows11_25H2_amd64

on: workflow_dispatch

permissions:
  contents: write

env:
  Build_VERSION: '26200.9168'
  FILE_NAME: Windows11_25H2_amd64
  
jobs:
  Windows11_25H2_amd64:
    runs-on: windows-latest

    steps:
    - name: Generate Timestamp
      id: time
      shell: pwsh
      run: |
        $timestamp = Get-Date -Format "yyyyMMddHHmm"
        echo "timestamp=$($timestamp.Trim())" >> $env:GITHUB_OUTPUT
        
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: UUP dump WinISO
      shell: cmd
      run: |
        cd ${{env.FILE_NAME}}
        dir
        uup_download_windows.cmd

    - name: dir dir
      shell: cmd
      run: |
        cd ${{env.FILE_NAME}}
        dir

    - name: Package binaries
      run: |
        7z a -t7z -v1780M -mx=0 zh-cn_${{env.FILE_NAME}}-${{env.Build_VERSION}}.7z ./${{env.FILE_NAME}}/*.iso
        
    - uses: actions/upload-artifact@v4
      with:
        name: zh-cn_${{env.FILE_NAME}}-${{env.Build_VERSION}}
        path: zh-cn_${{env.FILE_NAME}}-${{env.Build_VERSION}}.7z*

    - name: Release
      uses: softprops/action-gh-release@v3
      with:
        tag_name: ${{env.FILE_NAME}}
        overwrite_files: true
        body: |
            ## 🚀 Automated Release
            - **Product**: ${{ env.FILE_NAME }}
            - **Version**: ${{env.Build_VERSION}}
            - **Build Date**: ${{ steps.time.outputs.timestamp }}
            ---
            > ⚠️ **Note**: This is a multi-volume archive (.7z.001, .7z.002...). Please download all parts before extracting.
                   
        fail_on_unmatched_files: true
        name: zh-cn_${{env.FILE_NAME}}-${{env.Build_VERSION}}
        
        files: zh-cn_${{env.FILE_NAME}}-${{env.Build_VERSION}}.7z*


