name: Windows10_22H2_amd64

on: workflow_dispatch

permissions:
  contents: write

env:
  Build_VERSION: '19045.7663'
  FILE_NAME: Windows10_22H2_amd64
  
jobs:
  Windows10_22H2_amd64_Cumulative_Update:
    runs-on: windows-latest
    steps:
      
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: UUP dump WinISO
      shell: cmd
      run: |
        cd ${{ env.FILE_NAME }}
        
        echo =====Before 当前目录=====
        cd
        echo =====Before 当前目录下所有文件=====
        dir
        echo ============== Running ==============
        
        .\uup_download_windows.cmd
        
        echo ============== Execution completed ==============
        echo =====After 当前目录 =====
        cd
        echo =====After 当前目录下所有文件 =====
        dir

    - name: Compress with 7z
      shell: cmd
      run: |
        7z a -t7z -v1850M -mx=0 ${{ env.FILE_NAME }}_${{ env.Build_VERSION }}.7z .\${{ env.FILE_NAME }}\*.iso

    - name: Execution completed
      shell: pwsh
      run: |
        cd ${{env.FILE_NAME}}
       # Rename-Item -Path "*.iso" -NewName "${{ env.FILE_NAME }}_${{ env.Build_VERSION }}.iso"
        Write-Host "-----当前目录-----"
        pwd
        Write-Host "-----当前目录下的文件-----"
        ls
        Get-ChildItem | Select-Object Name, @{Name='Size(MB)';Expression={[math]::Round($_.Length / 1MB, 2)}}

   # - uses: actions/upload-artifact@v4
   #   with:
   #     name: ${{ env.FILE_NAME }}_${{ env.Build_VERSION }}
   #     path: ${{ env.FILE_NAME }}_${{ env.Build_VERSION }}.7z*

    - name: Release
      uses: softprops/action-gh-release@v3
      with:
        tag_name: ${{env.FILE_NAME}}
        fail_on_unmatched_files: true
        overwrite_files: true
        body: |
            ## 🚀 Automated Release
            - **Product**: ${{ env.FILE_NAME }}_Cumulative_Update_PRO
            - **Version**: ${{ env.Build_VERSION }}
            - **Language**: ZH_CN
            ---
            > ⚠️ **Note**: This is a multi-volume archive (.7z.001, .7z.002...). Please download all parts before extracting.
        name: ${{ env.FILE_NAME }}_${{ env.Build_VERSION }}
        files: ${{ env.FILE_NAME }}_${{ env.Build_VERSION }}.7z*


