name: Win7_x64_Ultimate_UpdatePack7R2
on: workflow_dispatch
permissions:
  contents: write
env:
  UpdatePack7R2_VERSION: '26.1.15'
  FILE_NAME: win7
  BASE_DIR: D:\a\UUPdump2ISO\UUPdump2ISO
jobs:
  Win7_x64_Ultimate_UpdatePack7R2:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: 1. Initialize Workspace
      shell: pwsh
      working-directory: .
      run: |
        mkdir -Force src
        mkdir -Force lib
        mkdir -Force utils
        mkdir -Force dist
        ls
        

        
    - name: 3. Download Utiles
      shell: pwsh
      working-directory: ./utils
      run: |
        # DirectX_June2010
        curl -L -o oscdimg.zip https://github.com/officialmofabs/oscdimg/raw/main/oscdimg-amd64.zip
        curl -L -o wimlib.zip https://wimlib.net/downloads/wimlib-1.14.5-windows-x86_64-bin.zip
        7z x oscdimg.zip -o"oscdimg" -y
        7z x wimlib.zip -o"wimlib" -y
        ls
        cd ./oscdimg
        ls
        cd ./wimlib
        ls


        

        