name: Windows10_22H2_amd64

on: workflow_dispatch

permissions:
  contents: write

env:
  Build_VERSION: '19045.7663'
  FILE_NAME: Windows10_22H2_amd64
  
jobs:
  Windows10_22H2_amd64_Cumulative_Update:
    runs-on: windows-latest
    steps:
      
    - name: Checkout repository
      uses: actions/checkout@v5


    - name: Delete Old Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: gh release delete ${{env.FILE_NAME}} --cleanup-tag -y || true


