name: Windows11_25H2_amd64

on: workflow_dispatch

permissions:
  contents: write

env:
  Build_VERSION: '26200.9278'
  FILE_NAME: Windows11_25H2_amd64
  
jobs:
  Windows11_25H2_amd64:
    runs-on: windows-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v5

    - name: UUP dump WinISO
      working-directory: ./Windows11_25H2_amd64
      shell: cmd
      run: |
        uup_download_windows.cmd

    - name: Split Archive
      working-directory: .
      shell: pwsh
      run: |
        7z a -t7z -v1750M -mx=0 ${{ env.FILE_NAME }}_${{ env.Build_VERSION }}.7z .\${{ env.FILE_NAME }}\*.iso
        
    - name: Delete Old Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: gh release delete ${{env.FILE_NAME}} --cleanup-tag -y || true

    - name: Build New Release
      uses: softprops/action-gh-release@v3
      with:
        overwrite_files: true
        fail_on_unmatched_files: true
        body: |
            ## 🚀 Automated Release
            - **Product**: ${{ env.FILE_NAME }}_PRO
            - **Version**: ${{ env.Build_VERSION }}
            - **Language**: ZH_CN
            ---
            > ⚠️ **Note**: This is a multi-volume archive (.7z.001, .7z.002...). Please download all parts before extracting.
        tag_name: ${{ env.FILE_NAME }}        
        name: ${{ env.FILE_NAME }}_${{ env.Build_VERSION }}
        files: ${{ env.FILE_NAME }}_${{ env.Build_VERSION }}.7z*