name: Windows7_x64

on: workflow_dispatch

permissions:
  contents: write

env:
  UpdatePack7R2_VERSION: '26.1.15'
  FILE_NAME: Windows7_x64
  BASE_DIR: D:\a\UUPdump2ISO\UUPdump2ISO
jobs:
  Windows7_x64_UpdatePack7R2:
    runs-on: windows-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Get Tools and Wim
      shell: pwsh
      run: |
        cd ${{ env.FILE_NAME }}
        Write-Host "-----当前目录-----"
        pwd
        Write-Host "-----当前目录下的文件-----"
        ls
        # dotNetFx48
        curl -L -o dotNetFx48_20260811_x64.WA https://github.com/abbodi1406/dotNetFx4xW7A/releases/download/26.08.11/dotNetFx48_20260811_x64.WA
        curl -L -o dotNetFx48_20260811_x86.WA https://github.com/abbodi1406/dotNetFx4xW7A/releases/download/26.08.11/dotNetFx48_20260811_x86.WA
        # dotNetFx48LP
        curl -L -o dotNetFx48LP_x64_CHS.WA https://github.com/abbodi1406/dotNetFx4xW7A/releases/download/19.04.13/dotNetFx48LP_x64_CHS.WA
        curl -L -o dotNetFx48LP_x86_CHS.WA https://github.com/abbodi1406/dotNetFx4xW7A/releases/download/19.04.13/dotNetFx48LP_x86_CHS.WA
        # vcredist
        curl -L -o vcredist_x64_Win7_20250708.WA https://gitlab.com/-/project/11037551/uploads/8899c68cf5b5bfc7da7f04b73afa9f58/vcredist_x64_Win7_20250708.WA
        curl -L -o vcredist_x86_Win7_20250708_r.WA https://gitlab.com/-/project/11037551/uploads/49d56348397669befad302f58070ab2f/vcredist_x86_Win7_20250708_r.WA
        # vcredist
        curl -L -o vcredist_x64_2022_WinAll_14.44.35211.WA https://gitlab.com/-/project/11037551/uploads/ce26d073600eb68db902bc12946d42e7/vcredist_x64_2022_WinAll_14.44.35211.WA
        curl -L -o vcredist_x86_2022_WinAll_14.44.35211_r.WA https://gitlab.com/-/project/11037551/uploads/16a7925f42634ef7232d7d9cc122034a/vcredist_x86_2022_WinAll_14.44.35211_r.WA
        # SmartFix
        curl -L -o SmartFix.exe https://smartfix.pro/SmartFix.exe
        # DirectX_June2010
        # UpdatePack7R2
        curl -L -o UpdatePack7R2.exe https://github.com/yuanpeirong/UpdatePack7R2/releases/download/UpdatePack7R2/UpdatePack7R2-26.1.15.exe
        # install_Windows7x64ULTIMATE.wim
        curl -L -o ${{ env.FILE_NAME }}.7z.001 https://github.com/yuanpeirong/UpdatePack7R2/releases/download/Windows7x64/install_Windows7x64ULTIMATE.7z.001
        curl -L -o ${{ env.FILE_NAME }}.7z.002 https://github.com/yuanpeirong/UpdatePack7R2/releases/download/Windows7x64/install_Windows7x64ULTIMATE.7z.002
        7z x ${{ env.FILE_NAME }}.7z.001
        Rename-Item -Path "*.wim" -NewName "${{ env.FILE_NAME }}.wim"
        Write-Host "=====当前目录====="
        pwd
        Write-Host "=====当前目录下的文件====="
        ls
        
    - name: Ready to begin
      shell: cmd
      run: |
        cd ${{env.FILE_NAME}}
        ren "*.wim" "${{ env.FILE_NAME }}.wim"
        echo =====当前目录=====
        cd
        echo =====当前目录下所有文件=====
        dir
        
    - name: UpdatePack7R2 Running
      shell: cmd
      run: |
        cd ${{ env.FILE_NAME }}
        echo =====当前目录=====
        cd
        echo =====当前目录下所有文件=====
        dir
        
        echo ============== UpdatePack7R2 Running ==============
        echo ============== ${{ env.BASE_DIR }}\${{ env.FILE_NAME }}\${{ env.FILE_NAME }}.wim ==============
        
        UpdatePack7R2.exe /ie11 /WimFile=${{ env.BASE_DIR }}\${{ env.FILE_NAME }}\${{ env.FILE_NAME }}.wim /Index=4 /NoUSB /Optimize=esd
        
        echo ============== UpdatePack7R2 Execution completed ==============
        
        echo =====After 当前目录=====
        cd
        echo =====After 当前目录下所有文件=====
        dir

    - name: Execution completed
      shell: pwsh
      run: |
        cd ${{env.FILE_NAME}}
        Write-Host "-----当前目录-----"
        pwd
        Write-Host "-----当前目录下的文件-----"
        ls
        
    - name: Mirrored product compression and splitting
      run: |
        7z a -t7z -v1950M -mx=0 ${{ env.FILE_NAME }}_${{ env.UpdatePack7R2_VERSION }}.7z ./${{ env.FILE_NAME }}.wim
        
        7z a -t7z -mx=0 UpdatePack7R2_log.7z C:\WINDOWS\UpdatePack7.log
        
    - name: Upload-Artifact
      shell: cmd
      run: |
        cd ${{env.FILE_NAME}}
        echo =====当前目录=====
        cd
        echo =====当前目录下所有文件=====
        dir
      
    - uses: actions/upload-artifact@v4
      with:
        name: UpdatePack7R2_log
        path: UpdatePack7R2_log.7z

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ env.FILE_NAME }}_${{ env.UpdatePack7R2_VERSION }}
        path: ${{ env.FILE_NAME }}_${{ env.UpdatePack7R2_VERSION }}.7z.*

    - name: Automated Release
      uses: softprops/action-gh-release@v3
      with:
        fail_on_unmatched_files: true
        overwrite_files: true        
        body: |
            ## 🚀 Automated Release
            - **Product**: ${{ env.FILE_NAME }}_SP1_旗舰版
            - **Version**: ${{ env.UpdatePack7R2_VERSION }}
            - **Language**: ZH_CN
            ---
            > ⚠️ **Note**: This is a multi-volume archive (.7z.001, .7z.002...). Please download all parts before extracting.
        tag_name: ${{ env.FILE_NAME }}
        name: ${{ env.FILE_NAME }}_${{ env.UpdatePack7R2_VERSION }}
        files: ${{ env.FILE_NAME }}_${{ env.UpdatePack7R2_VERSION }}.7z.*
